name:                ff
version:             0.1.0.0
github:              "washingt0/ff"
license:             BSD3
author:              "Washington Santos"
maintainer:          "washingtonstk@gmail.com"
copyright:           "2021 washingt0"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/washingt0/ff#readme>

dependencies:
- base >= 4.7 && < 5
- postgresql-simple
- text
- aeson
- bytestring
- servant
- servant-server
- wai
- warp
- resource-pool
- monad-control

library:
  source-dirs: src

executables:
  ff-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ff
    - postgresql-simple
    - text
    - aeson
    - bytestring
    - servant
    - servant-server
    - wai
    - warp
    - resource-pool
    - monad-control

tests:
  ff-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ff
